# Generated by Django 4.1.1 on 2022-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=64)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3/Summer')], default=1, max_length=1)),
                ('year', models.IntegerField(default=2022)),
                ('seat', models.IntegerField(default=99)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('courses', models.ManyToManyField(blank=True, related_name='enrolments', to='courses.course')),
            ],
        ),
    ]
